apiVersion: v1
kind: Secret
metadata:
  name: conv-secrets
type: Opaque
data:
  # Used in ...
  # RMQ + API
  RABBITMQ_DEFAULT_USER: bGVzc29ucw==
  RABBITMQ_DEFAULT_PASS: bGVzc29ucw==
  # API ONLY
  EXCHANGE: ZGVtb19leGNoYW5nZQ==
  RMQ_HOSTNAME: cm1xLWNsdXN0ZXJpcA==